sudo: false
language: erlang

script:
    - wget -c https://github.com/erlang/rebar3/releases/download/3.7.5/rebar3
    - chmod +x rebar3
    - ./rebar3 do compile, cover, dialyzer, ct 

otp_release:
    - 21.2
    - 20.3
